---
#1. Update apt packages to the latest version
- name: Update apt packages to the latest version
  apt:
    update_cache: yes

#2. check if mysql is already installed and if yes show a message to user
- name: Look for mysql
  shell: "dpkg -s mysql-server"
  ignore_errors: yes
  register: mysql_56_installed
  changed_when: no

- name: Important message
  debug:
    msg: |
      "MySQL experimental is already installed, make 'remove_experimental_mysql: true' in defaults/main.yml,
      if you want to remove it and install the stable version of MySQL"
  when: "'5.6.14' in  mysql_56_installed.stdout and not remove_experimental_mysql"


#3. Install mysql in the server
- name: Install MySQL from their community PPA
  apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.6"
    update_cache: yes
  when: ansible_distribution_release == 'precise'

- name: Install mysql and dependencies
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present
  with_items:
    - mysql-server
    - python-mysqldb

- name: Start mysql
  service:
    name: mysql
    state: started


#4. after installation add demo user with password 123456 to mysql
- name: add demo user to mysql
  mysql_user:
    name: demo
    password: 123456
    priv: '*.*:ALL'
    state: present


#5. restart mysql service
- name: restart mysql service
  service:
    name: mysql
    state: restarted
  tags:
    - "mysql_restart"

#6. make sure mysql service is back and running
- name: make sure mysql service is back and running
  service:
    name: mysql
    state: started
  tags:
    - "mysql_restart"
